package com.entity;
// Generated 08.Oca.2015 15:39:20 by Hibernate Tools 4.3.1



/**
 * Blogetiket generated by hbm2java
 */
public class Blogetiket  implements java.io.Serializable {


     private Integer beid;
     private Blog blog;
     private Etiket etiket;

    public Blogetiket() {
    }

    public Blogetiket(Blog blog, Etiket etiket) {
       this.blog = blog;
       this.etiket = etiket;
    }
   
    public Integer getBeid() {
        return this.beid;
    }
    
    public void setBeid(Integer beid) {
        this.beid = beid;
    }
    public Blog getBlog() {
        return this.blog;
    }
    
    public void setBlog(Blog blog) {
        this.blog = blog;
    }
    public Etiket getEtiket() {
        return this.etiket;
    }
    
    public void setEtiket(Etiket etiket) {
        this.etiket = etiket;
    }




}


