package com.entity;
// Generated 08.Oca.2015 15:39:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Etiket generated by hbm2java
 */
public class Etiket  implements java.io.Serializable {


     private Integer eid;
     private String EAd;
     private Set<Blogetiket> blogetikets = new HashSet<Blogetiket>(0);

    public Etiket() {
    }

	
    public Etiket(String EAd) {
        this.EAd = EAd;
    }
    public Etiket(String EAd, Set<Blogetiket> blogetikets) {
       this.EAd = EAd;
       this.blogetikets = blogetikets;
    }
   
    public Integer getEid() {
        return this.eid;
    }
    
    public void setEid(Integer eid) {
        this.eid = eid;
    }
    public String getEAd() {
        return this.EAd;
    }
    
    public void setEAd(String EAd) {
        this.EAd = EAd;
    }
    public Set<Blogetiket> getBlogetikets() {
        return this.blogetikets;
    }
    
    public void setBlogetikets(Set<Blogetiket> blogetikets) {
        this.blogetikets = blogetikets;
    }




}


